[pytest]
asyncio_mode = auto
pythonpath = .
testpaths = ./test_dir
python_files = test_*.py
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S